# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
   branches:
     include:
       - master
   paths:
     include:
       - mobile-samples/CoinTime/*

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: 'mobile-samples/CoinTime/CoinTime/CoinTime.Android.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: AndroidSigning@3
  inputs:
    apkFiles: '$(outputDirectory)/*.apk'
    apksignerKeystoreFile: 'debug.keystore'
    apksignerKeystorePassword: 'android'
    apksignerKeystoreAlias: 'androiddebugkey'
    apksignerKeyPassword: 'android'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'